import { NextApiRequest, NextApiResponse } from "next";

// eslint-disable-next-line no-unused-vars
type Handler = (req: NextApiRequest, res: NextApiResponse) => Promise<void>;

const allowCors =
  (fn: Handler) => async (req: NextApiRequest, res: NextApiResponse) => {
    res.setHeader("Access-Control-Allow-Credentials", "true");
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader(
      "Access-Control-Allow-Methods",
      "GET,OPTIONS,PATCH,DELETE,POST,PUT"
    );
    res.setHeader(
      "Access-Control-Allow-Headers",
      "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version"
    );

    if (req.method === "OPTIONS") {
      res.status(200).end();
      return;
    }
    return await fn(req, res);
  };

async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (!process.env.NEW_ANT_ORIGIN) {
    res.status(500).send({ msg: "New ant origin not found!" });
    return res.end();
  }

  if (
    !req.headers.origin ||
    req.headers.origin in
      ["https://www.typesofants.org", "http://www.typesofants.org"]
  ) {
    console.log("Wrong origin: ", req.headers.origin);
    res.status(405).send("Wrong origin!");
    return res.end();
  }

  const owner = "kaspar-p";
  const repo = "types-of-ants";
  if (process.env.GITHUB_TOKEN === undefined) {
    res.status(500).send({ msg: "Github token invalid!" });
    return res.end();
  }

  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/issues`,
    {
      method: "POST",
      headers: {
        Accept: "application/vnd.github.v3+json",
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
      },
      body: JSON.stringify({
        title: `<autogenerated> Add suggestion: \`${req.body}\``,
        body: `Autogenerated ant suggestion with body \`\`\`${req.body}\`\`\``,
        labels: ["enhancement", "bug", "autogenerated"],
      }),
    }
  );

  if (response.status === 201) {
    console.log("Successfully created issue!");
    res.status(200).send({ status: 200, msg: "Received ant suggestion!" });
    return res.end();
  } else {
    console.log("Error: did not create issue!");
    res
      .status(500)
      .send({ status: 500, msg: "Error while recording ant suggestion!" });
    return res.end();
  }
}

export default allowCors(handler);
// -------------------------
//    REED-SOLOMON ROUTES
// -------------------------

// // Sends back the PDF file of the paper
// router.get("/resume", async (req, res) => {
//   return res.sendFile("KasparPoland_Resume.pdf", {
//     root: "client/public/",
//   });
// });

// // -----------------
// //    TEST ROUTES
// // -----------------

// // Test GET method
// router.get("/test", (req, res) => {
//   return res.json({
//     path: "/api/dl/test",
//     method: "GET",
//     status: "SUCCESS",
//   });
// });

// // Test POST method
// router.post("/test", (req, res) => {
//   return res.json({
//     path: "/api/dl/test",
//     method: "POST",
//     status: "SUCCESS",
//   });
// });
