import Cors from "cors";
import { NextApiRequest, NextApiResponse } from "next";

interface corsRes {
  statusCode?: number | undefined;
  // eslint-disable-next-line no-unused-vars
  setHeader(key: string, value: string): any;
  end(): any;
}

const cors = Cors({
  methods: ["POST"],
});

function runMiddleware(req: Cors.CorsRequest, res: corsRes, fn: typeof cors) {
  return new Promise((resolve, reject) => {
    fn(req, res, (result) => {
      if (result instanceof Error) {
        return reject(result);
      }

      return resolve(result);
    });
  });
}

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  console.log(1);
  // Run cors middleware
  await runMiddleware(req, res, cors);

  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST");
  res.setHeader("Access-Control-Allow-Headers", "*");

  console.log(2);

  console.log(
    "Response has Access-Control-Allow-Origin header: ",
    res.hasHeader("Access-Control-Allow-Origin")
  );

  if (!process.env.NEW_ANT_ORIGIN) {
    res.status(500).send({ msg: "New ant origin not found!" });
    res.end();
  }

  console.log(3);

  if (
    !req.headers.origin ||
    process.env.NEW_ANT_ORIGIN !== req.headers.origin
  ) {
    console.log("Wrong origin: ", req.headers.origin);
    res.status(405).send("Wrong origin!");
    return res.end();
  }
  console.log("Got new ant suggestion: ", req.body);
  console.log(4);

  const owner = "kaspar-p";
  const repo = "types-of-ants";
  if (process.env.GITHUB_TOKEN === undefined) {
    res.status(500).send({ msg: "Github token invalid!" });
    res.end();
  }

  console.log(5);

  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/issues`,
    {
      method: "POST",
      headers: {
        Accept: "application/vnd.github.v3+json",
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
      },
      body: JSON.stringify({
        title: `<autogenerated> Add \`${req.body}\` ant`,
        body: `Autogenerated ant suggestion with body \`\`\`${req.body}\`\`\``,
        labels: ["enhancement", "bug", "autogenerated"],
      }),
    }
  );

  console.log(6);

  console.log(await response.json());

  if (response.status === 201) {
    console.log("Successfully created issue!");
    res.status(200).send({ status: 200, msg: "Received ant suggestion!" });
    return res.end();
  } else {
    console.log("Error: did not create issue!");
    res
      .status(500)
      .send({ status: 500, msg: "Error while recording ant suggestion!" });
    return res.end();
  }
}

// -------------------------
//    REED-SOLOMON ROUTES
// -------------------------

// // Sends back the PDF file of the paper
// router.get("/resume", async (req, res) => {
//   return res.sendFile("KasparPoland_Resume.pdf", {
//     root: "client/public/",
//   });
// });

// // -----------------
// //    TEST ROUTES
// // -----------------

// // Test GET method
// router.get("/test", (req, res) => {
//   return res.json({
//     path: "/api/dl/test",
//     method: "GET",
//     status: "SUCCESS",
//   });
// });

// // Test POST method
// router.post("/test", (req, res) => {
//   return res.json({
//     path: "/api/dl/test",
//     method: "POST",
//     status: "SUCCESS",
//   });
// });
