import { NextApiRequest, NextApiResponse } from "next";

export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  if (req.headers.host === "typesofants.org") {
    console.log("Got new ant suggestion: ", req.body);

    const owner = "kaspar-p";
    const repo = "types-of-ants";
    if (!process.env.GITHUB_TOKEN) {
      res.status(500).send({ msg: "Github token invalid!" });
    }

    fetch(`https://api.github.com/repos/${owner}/${repo}/issues`, {
      method: "POST",
      headers: {
        Accept: "application/vnd.github.v3+json",
        Authorization: `token ${process.env.GITHUB_TOKEN}`,
      },
      body: JSON.stringify({
        title: `<autogenerated> Add \`${req.body}\` ant`,
        body: `Autogenerated ant suggestion with body \`\`\`${req.body}\`\`\``,
        labels: ["enhancement", "bug"],
      }),
    })
      .then((response) => response.json())
      .then((json) => {
        console.log(json);
        return res.status(200).send({});
      });
  }
}

// -------------------------
//    REED-SOLOMON ROUTES
// -------------------------

// // Sends back the PDF file of the paper
// router.get("/resume", async (req, res) => {
//   return res.sendFile("KasparPoland_Resume.pdf", {
//     root: "client/public/",
//   });
// });

// // -----------------
// //    TEST ROUTES
// // -----------------

// // Test GET method
// router.get("/test", (req, res) => {
//   return res.json({
//     path: "/api/dl/test",
//     method: "GET",
//     status: "SUCCESS",
//   });
// });

// // Test POST method
// router.post("/test", (req, res) => {
//   return res.json({
//     path: "/api/dl/test",
//     method: "POST",
//     status: "SUCCESS",
//   });
// });
